version: "3"

services:
  api:
    # This is the latest LTS release of Node.js
    image: "node:10"
    user: node
    working_dir: /usr/src/app
    environment:
      - DATABASE_URL
      - GITHUB_API_KEY
      - LOOPBACK_API_PASSWORD
      - NODE_ENV=development
      - PORT=3000
      - STACKOVERFLOW_API_KEY
    volumes:
      - ./:/usr/src/app
    ports:
      - "127.0.0.1:${PORT:-3000}:3000"
    command: node_modules/.bin/nodemon .
